### PR TITLE
Replace generator url to https://generator.snowdrop.me

### PR DESCRIPTION
**Pull request by gytis**

### CODE REVIEW

**Comment by cmoulliard** [comment]
LGTM

**Comment by gytis** [comment]
Any idea why this didn't trigger a website build?

**Comment by cmoulliard** [comment]
Build has been triggered but an error has been reported if you look to the build view of the wnowdrop-site-angular-namespace

https://195.201.87.126:8443/console/project/snowdrop-site/browse/builds/snowdrop-site-angular/snowdrop-site-angular-12?tab=logs

@gytis

**Comment by gytis** [comment]
Ah I missed that. I've triggered a new buid

**Pull request merged**
